version: "2"

linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - rowserrcheck
    - staticcheck
    - testpackage
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl_v5
  disable:
    - gochecknoglobals
    - godox
    - err113
    - goheader
    - gomodguard
    - nlreturn
    - sqlclosecheck
    - depguard

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      simplify: true
