version: '3'
services:
  headlamp:
    image: ghcr.io/headlamp-k8s/headlamp:v0.44.0@sha256:b491653c1a0d380b70b67a4024f1204591f9c84a68ee567778d53d28b1856168
    command: ["--kubeconfig","/headlamp/config/config", "--port","64446", "--enable-dynamic-clusters"]
    restart: unless-stopped
    volumes:
      - ~/.kube/:/headlamp/config:ro
    ports:
      - 64446:64446
      - "30000-32000:30000-32000"
